# Generated by Django 4.1.5 on 2023-01-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelstations',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='prdct_id',
        ),
        migrations.AlterField(
            model_name='fuelstations',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
