# Generated by Django 4.1.5 on 2023-01-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_fuelstations_station_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('details', models.TextField(verbose_name='Job details')),
                ('qualifications', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name="User's Name")),
                ('usrName', models.CharField(max_length=35, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=500, verbose_name="User's Address")),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
