# Generated by Django 4.1.5 on 2023-01-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobs_user_alter_products_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.TextField(),
        ),
    ]
