# Generated by Django 4.1.5 on 2023-03-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fuelstations_last_login_alter_fuelstations_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='myAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
