# Generated by Django 4.1.5 on 2023-03-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_myadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelstations',
            name='last_login',
        ),
    ]
