# Generated by Django 4.1.5 on 2023-04-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_totalcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='job',
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jobs'),
        ),
    ]
